FROM public.ecr.aws/lambda/python:3.12

# Install git (required for hatch-vcs) and upgrade pip
RUN dnf install -y git && dnf clean all
RUN pip install --upgrade pip

# Copy source into /app
COPY . /app
WORKDIR /app

# Install your package system-wide (installs epic-images CLI)
RUN pip install --no-cache-dir .

# Copy the lambda handler into Lambda's runtime folder
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}

# Default command
CMD ["lambda_handler.handler"]
